POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento",
  "details": "",
  "maximunAttendees": 1
}

###

POST http://localhost:3333/events/0c086e93-0f5c-49c3-bad4-cee016c7b110/attendees
Content-Type: application/json

{
  "name": "Francisco Menezes",
  "email": "franciscomenezesbh1@gmail.com"
}

###

GET http://localhost:3333/events/382c214f-fcf3-4e72-a516-b4028b1d7d53
Content-Type: application/json
