POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento",
  "details": "",
  "maximunAttendees": 1
}

###

POST http://localhost:3333/events/0c086e93-0f5c-49c3-bad4-cee016c7b110/attendees
Content-Type: application/json

{
  "name": "Francisco Menezes",
  "email": "franciscomenezesbh1@gmail.com"
}

###

GET http://localhost:3333/events/d7833365-48d6-4021-ac95-79f885a8cc9d
Content-Type: application/json


###

GET http://localhost:3333/attendees/3/badge
Content-Type: application/json
